server:
  port: ${SERVER_PORT:6080}
  ssl:
    enabled: true
    
# LiveKit configuration
livekit:
  api:
    key: ${LIVEKIT_API_KEY:APIgu2Y3jMW8rUD}
    secret: ${LIVEKIT_API_SECRET:j4aEwDCtZejT2d5s8d9HprQtinKDFMoHkQhOxPjRegN}
    
