server:
  port: ${SERVER_PORT:6080}
  ssl:
    enabled: false
    
# LiveKit configuration
livekit:
  api:
    key: ${LIVEKIT_API_KEY:devkeydevkeydevkeydevkeydevkey}
    secret: ${LIVEKIT_API_SECRET:secretsecretsecretsecretsecret}
    
