server:
  port: 6080
  ssl:
    enabled: false
    
# LiveKit configuration
livekit:
  api:
    key: ${LIVEKIT_API_KEY:APINhUtuM6oBWvX}
    secret: ${LIVEKIT_API_SECRET:IxhqRNQBYBw5PfimyPHenJ2j9EMP2DNNof6DNXcGVyvB}
    
